import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { EmptyState } from '@/components/ui/EmptyState';
import { Input } from '@/components/ui/Input';
import { CatalogSkeleton } from './CatalogSkeleton';
import { PressableScale } from '@/components/ui/PressableScale';
import { useAppPalette } from '@/hooks/useAppPalette';
import { routes } from '@/constants/routes';
import { strings } from '@/constants/strings';
import { theme } from '@/constants/theme';
import { useCatalogItems } from '@/hooks/useCatalogItems';
import type { CatalogFilter, CatalogItem } from '@/types/catalog';
import { CatalogRow } from './CatalogRow';
const filters:CatalogFilter[]=['all','product','service'];
export function CatalogListScreen(){const palette=useAppPalette(),router=useRouter(),[search,setSearch]=useState(''),[filter,setFilter]=useState<CatalogFilter>('all');const{items,loading,error,refresh}=useCatalogItems(search,filter);const openItem=(item:CatalogItem)=>router.push({pathname:'/catalog-item/[id]',params:{id:item.id}});const empty=search.trim()?{title:strings.catalog.noResultsTitle,description:strings.catalog.noResultsDescription}:{title:strings.catalog.emptyTitle,description:strings.catalog.emptyDescription};return <SafeAreaView style={[styles.safeArea,{backgroundColor:palette.background}]} edges={['top','left','right']}>
<View style={styles.header}><View><Text style={styles.title}>{strings.catalog.title}</Text><Text style={styles.subtitle}>{strings.ux.productCatalog}</Text></View><View style={styles.count}><Text style={styles.countValue}>{items.length}</Text><Text style={styles.countLabel}>{strings.ux.productsFound}</Text></View></View>
<View style={styles.controls}><Input label={strings.catalog.searchLabel} placeholder={strings.catalog.searchPlaceholder} value={search} onChangeText={setSearch} returnKeyType="search"/><View style={styles.filters}>{filters.map(value=><Pressable key={value} accessibilityRole="button" accessibilityState={{selected:filter===value}} onPress={()=>setFilter(value)} style={[styles.filter,filter===value&&styles.filterActive]}><Ionicons name={value==='all'?'apps-outline':value==='product'?'cube-outline':'construct-outline'} size={17} color={filter===value?theme.colors.primary:theme.colors.textSecondary}/><Text style={[styles.filterText,filter===value&&styles.filterTextActive]}>{strings.catalog.filters[value]}</Text></Pressable>)}</View></View>
{loading?<CatalogSkeleton/>:error?<EmptyState title={strings.catalog.loadErrorTitle} description={strings.catalog.loadErrorDescription} icon="warning-outline" actionLabel={strings.common.retry} onAction={refresh}/>:<FlatList data={items} keyExtractor={item=>item.id} renderItem={({item})=><CatalogRow item={item} onPress={()=>openItem(item)}/>} contentContainerStyle={items.length===0?styles.emptyList:styles.list} ListEmptyComponent={<EmptyState title={empty.title} description={empty.description} icon="cube-outline"/>} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}/>}<PressableScale accessibilityLabel={strings.catalog.add} accessibilityRole="button" onPress={()=>router.push(routes.catalogItemNew)} wrapperStyle={styles.fabWrapper} style={[styles.fab,{backgroundColor:palette.primary}]}><Ionicons name="add" size={30} color={theme.colors.textOnPrimary}/></PressableScale></SafeAreaView>}
const styles=StyleSheet.create({safeArea:{flex:1,backgroundColor:theme.colors.background},header:{minHeight:84,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:theme.layout.screenHorizontalPadding},title:{color:theme.colors.textPrimary,...theme.typography.screenTitle},subtitle:{color:theme.colors.textSecondary,...theme.typography.caption,marginTop:theme.spacing[1]},count:{minWidth:60,alignItems:'center',padding:theme.spacing[2],backgroundColor:theme.colors.primarySoft,borderRadius:12},countValue:{color:theme.colors.primary,...theme.typography.sectionTitle},countLabel:{color:theme.colors.textSecondary,...theme.typography.caption},controls:{paddingHorizontal:theme.layout.screenHorizontalPadding,paddingBottom:theme.spacing[3],gap:theme.spacing[3]},filters:{flexDirection:'row',gap:theme.spacing[2]},filter:{flex:1,minHeight:42,flexDirection:'row',gap:theme.spacing[1],alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:theme.colors.border,borderRadius:12,backgroundColor:theme.colors.surface},filterActive:{backgroundColor:theme.colors.primarySoft,borderColor:theme.colors.primary},filterText:{color:theme.colors.textSecondary,...theme.typography.secondary},filterTextActive:{color:theme.colors.primary,fontWeight:'700'},list:{paddingTop:theme.spacing[1],paddingBottom:theme.layout.tabBarHeight+100},emptyList:{flexGrow:1,justifyContent:'center',paddingBottom:theme.layout.tabBarHeight},fabWrapper:{position:'absolute',right:theme.spacing[5],bottom:theme.layout.tabBarHeight+theme.spacing[4]},fab:{width:60,height:60,alignItems:'center',justifyContent:'center',backgroundColor:theme.colors.primary,borderRadius:22,elevation:6,shadowColor:'#000',shadowOpacity:.18,shadowRadius:8,shadowOffset:{width:0,height:4}},fabPressed:{backgroundColor:theme.colors.primaryPressed,transform:[{scale:.96}]}});
