export const routes = {
  onboarding: "/onboarding",
  dashboard: "/(tabs)/dashboard",
  invoices: "/(tabs)/invoices",
  invoiceNew: "/invoice/new",
  customers: "/(tabs)/customers",
  customerNew: "/customer/new",
  catalog: "/(tabs)/catalog",
  catalogItemNew: "/catalog-item/new",
  more: "/(tabs)/more",
  settings: "/settings",
  appearanceSettings: "/settings/appearance",
  businessSettings: "/settings/business",
  invoiceSettings: "/settings/invoice",
  notificationSettings: "/settings/notifications",
  aboutSettings: "/settings/about",
} as const;
