export const strings = {
  appName: "InvoiceFine",
  common: {
    archive: "Archive",
    cancel: "Cancel",
    chooseImage: "Choose image",
    loading: "Loading",
    notAvailable: "—",
    remove: "Remove",
    retry: "Try again",
    noResults: "No results found.",
    save: "Save business profile",
  },
  runtimeError: {
    title: "InvoiceFine hit an unexpected error",
    description:
      "Your saved business data is still stored locally. Try reopening this screen.",
    retry: "Try again",
  },
  startup: {
    loadingTitle: "Preparing InvoiceFine",
    loadingDescription: "Setting up secure local storage on this device.",
    errorTitle: "Local storage could not be prepared",
    errorDescription: "Check available device storage, then try again.",
  },
  onboarding: {
    eyebrow: "BUSINESS SETUP",
    title: "Set up your business",
    description:
      "Add the details that will appear on invoices and business records.",
    sections: {
      identity: "Business details",
      tax: "Tax settings",
      numbering: "Invoice numbering",
      branding: "Branding",
      printing: "Invoice page",
    },
    fields: {
      businessName: "Business name",
      address: "Business address",
      phone: "Phone number",
      email: "Email address",
      gstin: "GSTIN",
      stateCode: "State code",
      invoicePrefix: "Invoice prefix",
      nextInvoiceNumber: "Starting invoice number",
      taxEnabled: "Enable GST invoices",
      logo: "Business logo",
      signature: "Authorized signature",
      invoicePageSize: "Invoice page size",
    },
    helpers: {
      email: "Optional",
      gstin: "Required only when GST invoices are enabled",
      stateCode: "Two-digit Indian GST state code",
      invoicePrefix: "For example: INV",
      logo: "Optional square image",
      signature: "Optional signature image",
    },
    validation: {
      required: "This field is required.",
      phone: "Enter a valid 10-digit Indian mobile number.",
      email: "Enter a valid email address.",
      gstin: "Enter a valid 15-character GSTIN.",
      stateCode: "Enter a valid two-digit state code.",
      invoicePrefix: "Use 2–10 letters, numbers, hyphens, or slashes.",
      invoiceNumber: "Enter a whole number greater than zero.",
    },
    messages: {
      imageErrorTitle: "Image could not be selected",
      imageErrorDescription: "Please try another image.",
      saveErrorTitle: "Profile could not be saved",
      saveErrorDescription: "Check the details and try again.",
    },
  },
  customers: {
    title: "Customers",
    add: "Add customer",
    editTitle: "Customer details",
    newTitle: "New customer",
    formDescription: "Save contact, tax, and billing details.",
    sections: {
      contact: "Contact details",
      tax: "Tax and billing",
      notes: "Additional notes",
    },
    searchLabel: "Search customers",
    searchPlaceholder: "Search by name or phone",
    emptyTitle: "No customers yet",
    emptyDescription:
      "Add your first customer to begin building a customer list.",
    noResultsTitle: "No matching customers",
    noResultsDescription: "Try a different customer name or phone number.",
    loadErrorTitle: "Customers could not be loaded",
    loadErrorDescription: "Check local storage and try again.",
    detailErrorTitle: "Customer could not be loaded",
    detailErrorDescription: "Return to the customer list and try again.",
    fields: {
      name: "Customer name",
      phone: "Phone number",
      email: "Email address",
      gstin: "GSTIN",
      stateCode: "State code",
      billingAddress: "Billing address",
      notes: "Notes",
    },
    helpers: {
      optional: "Optional",
      stateCode: "Optional two-digit Indian GST state code",
    },
    actions: {
      create: "Save customer",
      update: "Update customer",
      archive: "Archive customer",
    },
    messages: {
      createErrorTitle: "Customer could not be saved",
      updateErrorTitle: "Customer could not be updated",
      saveErrorDescription: "Check the details and try again.",
      updateSuccessTitle: "Customer updated",
      updateSuccessDescription: "The customer details were saved.",
      archiveTitle: "Archive this customer?",
      archiveDescription:
        "The customer will be hidden from the active customer list.",
      archiveErrorTitle: "Customer could not be archived",
      archiveErrorDescription: "Please try again.",
    },
    validation: {
      phone: "Enter a valid 10-digit Indian mobile number or leave it blank.",
      gstin: "Enter a valid 15-character GSTIN or leave it blank.",
      stateCode: "Enter a valid two-digit state code or leave it blank.",
    },
  },
  catalog: {
    title: "Catalog",
    add: "Add item",
    newTitle: "New catalog item",
    editTitle: "Item details",
    searchLabel: "Search catalog",
    searchPlaceholder: "Search by name, SKU, or barcode",
    filters: { all: "All", product: "Products", service: "Services" },
    types: { product: "Product", service: "Service" },
    emptyTitle: "Catalog is empty",
    emptyDescription:
      "Add a product or service to begin building your catalog.",
    noResultsTitle: "No matching items",
    noResultsDescription: "Try another name, SKU, or barcode.",
    loadErrorTitle: "Catalog could not be loaded",
    loadErrorDescription: "Check local storage and try again.",
    detailErrorTitle: "Item could not be loaded",
    detailErrorDescription: "Return to the catalog and try again.",
    sections: {
      identity: "Item details",
      pricing: "Pricing and tax",
      inventory: "Inventory settings",
    },
    fields: {
      type: "Item type",
      name: "Item name",
      sku: "SKU",
      barcode: "Barcode",
      category: "Category",
      brand: "Brand",
      unit: "Unit",
      purchasePrice: "Purchase price",
      sellingPrice: "Selling price",
      gstRate: "GST rate (%)",
      lowStockThreshold: "Low-stock threshold",
    },
    helpers: {
      optional: "Optional",
      unit: "For example: pcs, kg, hour",
      money: "Enter rupees, for example 125.50",
      gstRate: "Enter 0–100",
      stock:
        "Current stock begins at zero. Stock movements are added in a later milestone.",
      threshold: "Supports up to three decimal places",
    },
    actions: {
      create: "Save item",
      update: "Update item",
      archive: "Archive item",
    },
    messages: {
      createErrorTitle: "Item could not be saved",
      updateErrorTitle: "Item could not be updated",
      saveErrorDescription:
        "Check the details. SKU and barcode must be unique.",
      updateSuccessTitle: "Item updated",
      updateSuccessDescription: "The catalog item was saved.",
      archiveTitle: "Archive this item?",
      archiveDescription: "The item will be hidden from the active catalog.",
      archiveErrorTitle: "Item could not be archived",
      archiveErrorDescription: "Please try again.",
    },
    validation: {
      money: "Enter a valid amount with up to two decimal places.",
      gstRate: "Enter a valid GST rate from 0 to 100.",
      quantity:
        "Enter a non-negative quantity with up to three decimal places.",
    },
  },
  invoiceDrafts: {
    title: "Invoices",
    add: "New invoice",
    newTitle: "New invoice draft",
    editTitle: "Edit invoice draft",
    emptyTitle: "No invoice drafts",
    emptyDescription: "Create an invoice draft to begin.",
    loadErrorTitle: "Drafts could not be loaded",
    loadErrorDescription: "Check local storage and try again.",
    detailErrorTitle: "Draft could not be loaded",
    detailErrorDescription: "Return to invoices and try again.",
    draftLabel: "Draft",
    customer: "Customer",
    noCustomer: "No customer selected",
    selectCustomer: "Select customer",
    invoiceType: "Invoice type",
    taxInvoice: "Tax invoice",
    nonTaxInvoice: "Non-tax invoice",
    invoiceDate: "Invoice date",
    dueDate: "Due date",
    dateHelper: "Use YYYY-MM-DD",
    notes: "Notes",
    optional: "Optional",
    lineItems: "Line items",
    addItem: "Add item",
    noItems: "Add at least one product or service.",
    quantity: "Quantity",
    unitPrice: "Unit price",
    discount: "Discount",
    removeLine: "Remove",
    totals: "Totals",
    subtotal: "Subtotal",
    totalDiscount: "Discount",
    taxable: "Taxable amount",
    cgst: "CGST",
    sgst: "SGST",
    igst: "IGST",
    rounding: "Rounding",
    total: "Total",
    save: "Save draft",
    savedTitle: "Draft saved",
    savedDescription: "The invoice draft is available offline.",
    saveErrorTitle: "Draft could not be saved",
    saveErrorDescription: "Check customer state, dates, and line item values.",
    invalidDate: "Enter a valid date as YYYY-MM-DD.",
    invalidLines: "Check quantity, price, and discount values.",
    selectItemTitle: "Choose an item",
    selectCustomerTitle: "Choose a customer",
    close: "Close",
  },
  finalization: {
    finalize: "Finalize invoice",
    finalizeTitle: "Finalize this invoice?",
    finalizeDescription:
      "This allocates the invoice number and updates product stock. It cannot be silently edited afterward.",
    finalizeErrorTitle: "Invoice could not be finalized",
    finalizeErrorDescription:
      "Check the draft, customer state, and catalog products.",
    finalizedTitle: "Invoice finalized",
    invoiceNumber: "Invoice number",
    cancelInvoice: "Cancel invoice",
    cancelTitle: "Cancel this invoice?",
    cancelDescription:
      "Eligible product stock will be restored through reversal entries.",
    cancelErrorTitle: "Invoice could not be cancelled",
    cancelErrorDescription: "Invoices with payments cannot be cancelled.",
    cancelledTitle: "Invoice cancelled",
    detailsTitle: "Invoice details",
    lineItems: "Line items",
    status: {
      draft: "Draft",
      finalized: "Finalized",
      partially_paid: "Partially paid",
      paid: "Paid",
      overdue: "Overdue",
      cancelled: "Cancelled",
    },
  },
  pdf: {
    print: "Print invoice",
    share: "Share PDF",
    preparing: "Preparing PDF",
    errorTitle: "PDF could not be created",
    errorDescription: "Please try again.",
    a4: "A4",
    compact: "4 × 6 inch",
    profileTitle: "Business profile and invoice page",
  },
  payments: {
    record: "Record payment",
    title: "New payment",
    amount: "Amount",
    date: "Payment date",
    method: "Payment method",
    reference: "Reference",
    notes: "Notes",
    save: "Save payment",
    outstanding: "Outstanding",
    paid: "Paid",
    history: "Payment history",
    successTitle: "Payment saved",
    errorTitle: "Payment could not be saved",
    errorDescription: "Check the amount and outstanding balance.",
    ledger: "Customer ledger",
    invoiced: "Total invoiced",
    received: "Total received",
    noEntries: "No ledger entries yet.",
    methods: {
      cash: "Cash",
      upi: "UPI",
      card: "Card",
      bank_transfer: "Bank transfer",
      cheque: "Cheque",
      other: "Other",
    },
  },
  expenses: {
    title: "Expenses",
    add: "Add expense",
    empty: "No expenses yet.",
    category: "Category",
    date: "Expense date",
    amount: "Amount",
    payee: "Payee",
    notes: "Notes",
    save: "Save expense",
    saved: "Expense saved",
    errorTitle: "Expense could not be saved",
    report: "Profit report",
    startDate: "Start date",
    endDate: "End date",
    apply: "Apply range",
    sales: "Sales revenue",
    cogs: "Cost of goods sold",
    gross: "Gross profit",
    totalExpenses: "Expenses",
    net: "Net profit",
    dateHelp: "Use YYYY-MM-DD",
  },
  reports: {
    today: "Today",
    month: "This month",
    custom: "Custom",
    startDate: "Start date",
    endDate: "End date",
    apply: "Apply",
    sales: "Sales",
    received: "Received",
    receivables: "Receivables",
    cogs: "COGS",
    expenses: "Expenses",
    gross: "Gross profit",
    net: "Net profit",
    customers: "Customers",
    lowStock: "Low stock",
    recentInvoices: "Recent invoices",
    lowStockItems: "Low-stock items",
    noInvoices: "No recent invoices.",
    noLowStock: "No low-stock items.",
    errorTitle: "Dashboard could not be loaded",
    errorDescription: "Check local storage and try again.",
  },
  ux: {
    brand: "InvoiceFine",
    tagline: "Pocket ERP for Indian Small Business",
    quickActions: "Quick actions",
    createInvoice: "Create invoice",
    addCustomer: "Add customer",
    addProduct: "Add product",
    pendingPayments: "Pending payments",
    viewAll: "View all",
    stockLeft: "left",
    needsAttention: "Needs attention",
    searchItems: "Search name, SKU or barcode",
    recent: "Recent",
    selectedItems: "items selected",
    decreaseQuantity: "Decrease quantity",
    increaseQuantity: "Increase quantity",
    productsFound: "items",
    stock: "Stock",
    inStock: "In stock",
    lowStockLabel: "Low stock",
    outOfStock: "Out of stock",
    edit: "Edit",
    open: "Open",
    swipeHint: "Swipe left for quick action",
    productCatalog: "Products and services for faster billing",
    dashboardHeroDescription: "Fast billing, stock and professional PDF",
    customerSubtitle: "People, balances and business history",
    moreSubtitle: "Manage your business and financial tools",
    moreSection: "Business tools",
    profileDescription: "Invoice identity, GST and page size",
    expensesDescription: "Record and review business spending",
    profitDescription: "Understand sales, costs and profit",
    legalDescription: "Policies, licenses and local-data controls",
  },
  customerProfile: {
    overview: "Customer overview",
    totalSales: "Total sales",
    outstanding: "Outstanding",
    received: "Received",
    invoices: "Invoices",
    call: "Call",
    whatsapp: "WhatsApp",
    edit: "Edit profile",
    ledger: "View ledger",
    lastInvoice: "Last invoice",
    lastPayment: "Last payment",
    noInvoice: "No invoice yet",
    noPayment: "No payment yet",
    contactUnavailable: "Phone number is not available.",
    contactError: "Could not open this action.",
    activity: "Recent activity",
  },
  analytics: {
    title: "Business reports",
    subtitle: "See what is growing your business",
    overview: "Profit overview",
    monthlySales: "Monthly sales",
    monthlyProfit: "Monthly profit",
    expenseBreakdown: "Expense breakdown",
    topProducts: "Top products",
    noChartData: "No data in this date range.",
    sold: "sold",
    ofExpenses: "of expenses",
    refreshError:
      "Report could not be loaded. Check the date range and try again.",
    salesByCategory: "Sales by category",
    paymentStatus: "Paid vs pending",
    paid: "Paid",
    pending: "Pending",
    selected: "Selected",
    clearFilter: "Clear filter",
    categories: "categories",
  },
  tabs: {
    dashboard: "Dashboard",
    invoices: "Invoices",
    customers: "Customers",
    catalog: "Catalog",
    products: "Products",
    services: "Services",
    reports: "Reports",
    more: "More",
  },
  dashboard: {
    eyebrow: "BUSINESS OVERVIEW",
    title: "Dashboard",
    description:
      "Your business summary will appear here as you begin using InvoiceFine.",
    summaryTitle: "Summary",
    recentTitle: "Recent activity",
    metrics: {
      sales: "Today's sales",
      received: "Payments received",
      receivables: "Pending receivables",
      stock: "Low-stock items",
    },
    metricPlaceholder: "Available after setup",
    emptyTitle: "No activity yet",
    emptyDescription:
      "Recent invoices and payments will appear here in a future milestone.",
  },
  placeholders: {
    invoices: {
      title: "No invoices yet",
      description: "Invoice management will be added in a future milestone.",
    },
    catalog: {
      title: "Catalog is empty",
      description: "Products and services will be added in a future milestone.",
    },
    more: {
      title: "More tools",
      description:
        "Settings and additional tools will be added in future milestones.",
    },
  },
} as const;
