import type { VerticalInvoiceDetails } from "./vertical-workflow";
import type { InvoicePageSize } from "./business";
import type { InvoiceKind } from "./invoice";
export type InvoicePdfLine = {
  description: string;
  sku: string | null;
  unit: string | null;
  quantityScaled: number;
  unitPricePaise: number;
  discountPaise: number;
  gstRateBasisPoints: number;
  lineTotalPaise: number;
};
export type InvoicePdfData = {
  kind: InvoiceKind;
  invoiceNumber: string;
  invoiceDate: string;
  dueDate: string | null;
  customerName: string | null;
  customerAddress: string | null;
  customerGstin: string | null;
  businessName: string;
  businessAddress: string;
  businessPhone: string;
  businessGstin: string | null;
  businessLogoUri: string | null;
  businessSignatureUri: string | null;
  subtotalPaise: number;
  discountPaise: number;
  cgstPaise: number;
  sgstPaise: number;
  igstPaise: number;
  roundingPaise: number;
  totalPaise: number;
  paidPaise: number;
  settlementDiscountPaise: number;
  notes: string | null;
  pageSize: InvoicePageSize;
  verticalDetails: VerticalInvoiceDetails | null;
  lines: InvoicePdfLine[];
};
