import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { strings } from '@/constants/strings';
import { theme } from '@/constants/theme';
export type SelectionOption={id:string;title:string;subtitle?:string};
export function SelectionModal({visible,title,options,onSelect,onClose}:{visible:boolean;title:string;options:SelectionOption[];onSelect:(id:string)=>void;onClose:()=>void}){
 return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><SafeAreaView style={styles.safe}><View style={styles.header}><Text style={styles.title}>{title}</Text><Pressable accessibilityRole="button" onPress={onClose} style={styles.close}><Text style={styles.closeText}>{strings.invoiceDrafts.close}</Text></Pressable></View><ScrollView>{options.map((option)=><Pressable key={option.id} accessibilityRole="button" onPress={()=>onSelect(option.id)} style={({pressed})=>[styles.row,pressed&&styles.pressed]}><Text style={styles.option}>{option.title}</Text>{option.subtitle?<Text style={styles.subtitle}>{option.subtitle}</Text>:null}</Pressable>)}</ScrollView></SafeAreaView></Modal>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:theme.colors.background},header:{minHeight:theme.layout.headerHeight,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:theme.layout.screenHorizontalPadding},title:{color:theme.colors.textPrimary,...theme.typography.sectionTitle},close:{minHeight:theme.layout.minimumTouchTarget,justifyContent:'center'},closeText:{color:theme.colors.primary,...theme.typography.body},row:{paddingHorizontal:theme.layout.screenHorizontalPadding,paddingVertical:theme.spacing[4],backgroundColor:theme.colors.surface,borderBottomColor:theme.colors.border,borderBottomWidth:theme.layout.borderWidth},pressed:{backgroundColor:theme.colors.primarySoft},option:{color:theme.colors.textPrimary,...theme.typography.body},subtitle:{color:theme.colors.textSecondary,...theme.typography.secondary}});
