import {
  verticalDetailEntries,
  workflowTitle,
} from "../../lib/vertical-details";
import type { InvoicePdfData } from "../../types/invoice-pdf";

const escapeHtml = (value: string | null | undefined) =>
  String(value ?? "").replace(
    /[&<>"']/g,
    (character) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        character
      ] ?? character,
  );
const money = (value: number) => `₹${(value / 100).toFixed(2)}`;
const quantity = (value: number) =>
  (value / 1000).toFixed(3).replace(/\.?0+$/, "");

export function createInvoiceHtml(data: InvoicePdfData): string {
  const size = data.pageSize === "a4" ? "A4" : "4in 6in";
  const compact = data.pageSize === "4x6";
  const itemRows = data.lines
    .map(
      (line, index) =>
        `<tr><td>${index + 1}</td><td>${escapeHtml(line.description)}${
          line.sku ? `<small>${escapeHtml(line.sku)}</small>` : ""
        }</td><td>${quantity(line.quantityScaled)} ${escapeHtml(line.unit)}</td><td>${money(
          line.unitPricePaise,
        )}</td><td>${line.gstRateBasisPoints / 100}%</td><td>${money(
          line.lineTotalPaise,
        )}</td></tr>`,
    )
    .join("");
  const verticalRows = data.verticalDetails
    ? verticalDetailEntries(data.verticalDetails)
        .map(
          (row) =>
            `<div class="detail-row"><span>${escapeHtml(row.label)}</span><b>${escapeHtml(
              row.value,
            )}</b></div>`,
        )
        .join("")
    : "";
  const verticalSection =
    data.verticalDetails && verticalRows
      ? `<section class="job box"><h3>${escapeHtml(
          workflowTitle(data.verticalDetails.workflow),
        )}</h3>${verticalRows}</section>`
      : "";

  return `<!doctype html><html><head><meta charset="utf-8"><style>
@page{size:${size};margin:${compact ? "5mm" : "12mm"}}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#19191b;font-size:${
    compact ? "9px" : "11px"
  };margin:0}header{display:flex;justify-content:space-between;border-bottom:2px solid #d93632;padding-bottom:8px}h1{margin:0;color:#d93632;font-size:${
    compact ? "18px" : "24px"
  }}h2,h3{margin:0 0 4px}.meta{text-align:right}.parties{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:10px 0}.box{border:1px solid #d7d7db;border-radius:7px;padding:8px}.job{margin:10px 0}.detail-row{display:grid;grid-template-columns:38% 62%;gap:8px;padding:3px 0;border-bottom:1px solid #ededf0}.detail-row span{color:#62626a}table{width:100%;border-collapse:collapse}th,td{border-bottom:1px solid #d7d7db;padding:${
    compact ? "4px 2px" : "6px 4px"
  };text-align:right}th:nth-child(2),td:nth-child(2){text-align:left}small{display:block;color:#6b7280}.totals{margin:10px 0 0 auto;width:${
    compact ? "65%" : "45%"
  }}.totals div{display:flex;justify-content:space-between;padding:3px}.grand{font-weight:bold;border-top:2px solid #19191b;font-size:1.15em}.notes{margin-top:10px}.footer{margin-top:12px;text-align:center;color:#6b7280}</style></head><body>
<header><div><h1>${escapeHtml(data.businessName)}</h1><div>${escapeHtml(
    data.businessAddress,
  )}</div><div>${escapeHtml(data.businessPhone)}</div>${
    data.businessGstin
      ? `<div>GSTIN: ${escapeHtml(data.businessGstin)}</div>`
      : ""
  }</div><div class="meta"><h2>INVOICE</h2><b>${escapeHtml(
    data.invoiceNumber,
  )}</b><div>Date: ${escapeHtml(data.invoiceDate)}</div>${
    data.dueDate ? `<div>Due: ${escapeHtml(data.dueDate)}</div>` : ""
  }</div></header>
<section class="parties"><div class="box"><b>Bill to</b><div>${
    escapeHtml(data.customerName) || "Cash customer"
  }</div><div>${escapeHtml(data.customerAddress)}</div>${
    data.customerGstin
      ? `<div>GSTIN: ${escapeHtml(data.customerGstin)}</div>`
      : ""
  }</div><div class="box"><b>Page format</b><div>${
    data.pageSize === "a4" ? "A4" : "4 × 6 inch"
  }</div></div></section>${verticalSection}
<table><thead><tr><th>#</th><th>Item</th><th>Qty</th><th>Rate</th><th>GST</th><th>Amount</th></tr></thead><tbody>${itemRows}</tbody></table>
<div class="totals"><div><span>Subtotal</span><span>${money(
    data.subtotalPaise,
  )}</span></div>${
    data.discountPaise
      ? `<div><span>Discount</span><span>-${money(data.discountPaise)}</span></div>`
      : ""
  }${data.cgstPaise ? `<div><span>CGST</span><span>${money(data.cgstPaise)}</span></div>` : ""}${
    data.sgstPaise
      ? `<div><span>SGST</span><span>${money(data.sgstPaise)}</span></div>`
      : ""
  }${data.igstPaise ? `<div><span>IGST</span><span>${money(data.igstPaise)}</span></div>` : ""}<div><span>Rounding</span><span>${money(
    data.roundingPaise,
  )}</span></div><div class="grand"><span>Total</span><span>${money(
    data.totalPaise,
  )}</span></div></div>${
    data.notes
      ? `<div class="notes"><b>Notes:</b> ${escapeHtml(data.notes)}</div>`
      : ""
  }<div class="footer">Generated by InvoiceFine</div></body></html>`;
}
